### ISSUE TITLE
To run?

### ISSUE THREAD

**Issue by stuartn60** [ishanshukla97/deep-builder-demo#6]
Hi ... thanks for this project ... I'm not having success in running it from either on your demo website http://34.105.203.41/ or local ... what cmds to run locally pls? ... I've used:
`git clone https://github.com/ishanshukla97/deep-builder-demo.git`
`docker build --tag deepbuilder:1.0 .`
`docker run --publish 8000:8080 --detach --name db deepbuilder:1.0`
... curl localhost:8000 gives `curl: (56) Recv failure: Connection reset by peer`
... docker ps gives ports `80/tcp, 0.0.0.0:8000->8080/tcp`
... ip r gives `172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1`
... in cypress.json I see `"baseUrl": "http://localhost:3000/"` but 3000 as container url port doesn't seem to help
[... btw I'm using opensuse tumbleweed, docker 19.03.12 & this checker works fine: https://github.com/crccheck/docker-hello-world]

**Comment by ishanshukla97** [comment]
Could you clone the repo and simply do 
```yarn```
```yarn start```

**Comment by ishanshukla97** [comment]
You could do it with docker too. Just tested this and it runs fine.
Build and run
```docker run --rm -it  -p 80:80/tcp <image name>```
If it doesn't send, send me logs too

**Comment by stuartn60** [comment]
Hi Ishan ...your docker cmd works fine ... an impressive network builder!
... thanks, Stuart

**Comment by stuartn60** [comment]
yarn works fine too ... thanks ... a few messages ...

Compiled with warnings.

./src/components/Node/NodeModel.ts
 Line 1:56:  'DefaultNodeModel' is defined but never used
@typescript-eslint/no-unused-vars

./src/services/playground.ts
 Line 28:20:  Expected to return a value in arrow function
array-callback-return

./src/components/OpsWidget/Item.tsx
 Line 2:10:  'Label' is defined but never used
@typescript-eslint/no-unused-vars

./src/pages/FAQ/FAQ.tsx
 Line 2:21:  'Header' is defined but never used
@typescript-eslint/no-unused-vars

./src/components/Node/index.tsx
 Line 46:53:  Expected to return a value at the end of arrow function
array-callback-return
 Line 96:48:  Unexpected string concatenation of literals
no-useless-concat

./src/components/PlaygroundWidget/index.tsx
 Line 4:21:   'Button' is defined but never used
@typescript-eslint/no-unused-vars
 Line 4:29:   'Input' is defined but never used
@typescript-eslint/no-unused-vars
 Line 23:12:  'state' is assigned a value but never used
@typescript-eslint/no-unused-vars
 Line 36:11:  'handleName' is assigned a value but never used
@typescript-eslint/no-unused-vars

./src/pages/ModelBuilder.tsx
 Line 4:28:    'NodeModelListener' is defined but never used

@typescript-eslint/no-unused-vars
 Line 101:8:   React Hook useEffect has missing dependencies: 'diagramApp',
'forceRender', and 'prevSelectedNode'. Either include them or remove the
dependency array  react-hooks/exhaustive-deps
 Line 114:8:   React Hook useEffect has a missing dependency: 'diagramApp'.
Either include it or remove the dependency array
                                          react-hooks/exhaustive-deps
 Line 194:23:  'downloadResult' is assigned a value but never used

@typescript-eslint/no-unused-vars
 Line 305:15:  'modelInput' is assigned a value but never used

@typescript-eslint/no-unused-vars

./src/components/PropertyPane/index.tsx
 Line 90:21:  Arrow function expected a return value  array-callback-return

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by ishanshukla97** [comment]
Thanks 😃 !
Closing this.
