### ISSUE TITLE
Docs: Add CONTRIBUTIONS.md for contribution guidelines

### ISSUE THREAD

**Issue by ishanshukla97** [ishanshukla97/deep-builder-demo#8]
This file outlines contribution guidelines.

**Comment by Vrindagupta6828** [comment]
@ishanshukla97  i want to work on this please assign

**Comment by Vrindagupta6828** [comment]
@ishanshukla97  i just have to add the contributors.ms folder right?

**Comment by ishanshukla97** [comment]
No. Add a contributions.md file at the root of the project. In that file write contribution guidelines. For start write this:

---
1) All PRs must address some issue. If you think you can improve something in this project, make an issue first.
2) After making the necessary changes, run `yarn test` and make sure all tests pass. If something fails, make those tests pass.
3) PRs with failing tests would be marked as invalid/spam
4) In draft of PR description mention issue like: Closes #<issue number>
---

**Comment by Vrindagupta6828** [comment]
@ishanshukla97 I have added and created a PR #10 please check it and merge it if there are no issues.
