### ISSUE TITLE
Docs: Update readme with run instructions

### ISSUE THREAD

**Issue by ishanshukla97** [ishanshukla97/deep-builder-demo#9]
Headover to issues with title 'to run?` In that I have outlined commands to run this repo. Gist being:
If you have node and npm installed
- Clone this repo
- yarn
- yarn run
- For testing: yarn test
If you have docker installed:
- Clone this repo
- docker build . -t <your image/tag name>
- docker run --rm -it -p 80:80/tcp <image name>

**Comment by gioboa** [comment]
Can I take this?
